#!/bin/sh
#Copyright (c) 2024 Qualcomm Technologies, Inc.
#All Rights Reserved.
#Confidential and Proprietary - Qualcomm Technologies, Inc.
set -e

device=$1
if [ "$device" = "" ]; then
    echo "Usage: zram-swap-init <device>"
    exit 1
fi
echo "zram-swap-init called" > /dev/kmsg
# Allocate zram to be 75% of the size of actual system memory
# Note: zram is only allocated when used. When swapped pages compress with a
# a 2:1 ratio zram will require 37.5% of system memory (while allowing to use
# 137.5% memory).
ZRAM_SIZE_PERCENT=75
# Try loading zram module
modprobe -q zram || true
if [ $(grep 'lz4' /sys/devices/virtual/block/zram0/comp_algorithm | wc -w) -gt 0 ]; then
	ZRAM_ALGORITHM=lz4
elif [ $(grep '\[lzo\]' /sys/devices/virtual/block/zram0/comp_algorithm | wc -w) -gt 0 ]; then
	ZRAM_ALGORITHM=lzo
elif [ $(grep '\[lzo-rle\]' /sys/devices/virtual/block/zram0/comp_algorithm | wc -w) -gt 0 ]; then
	ZRAM_ALGORITHM=lzo-rle
elif [ $(grep '\[zstd\]' /sys/devices/virtual/block/zram0/comp_algorithm | wc -w) -gt 0 ]; then
	ZRAM_ALGORITHM=zstd
fi
[ -f /etc/default/zram ] && . /etc/default/zram || true

memtotal=$(grep MemTotal /proc/meminfo | awk ' { print $2 } ')
memzram=$(($memtotal*${ZRAM_SIZE_PERCENT}/100))
if [ $memzram -gt 6291456 ]; then
	memzram=6291456
fi

zramctl -a ${ZRAM_ALGORITHM} -s ${memzram}KB $device
mkswap -L "zram-swap" $device
swapon $device -p 32758
