#!/bin/sh
#
# qwes_license_store        init.d script to set up QWES license store.
#
#Copyright (c) 2020-2024 Qualcomm Technologies, Inc.
#All Rights Reserved.
#Confidential and Proprietary - Qualcomm Technologies, Inc.


set -e

PFM_PATH=/var/persist/qtee_supplicant/pfm/
OEM_QWES_OVERRIDE_LICENSE_STORE="${PFM_PATH}"/licenses/

echo "Creating QWES LICENSE STORE : $OEM_QWES_OVERRIDE_LICENSE_STORE" > /dev/kmsg
mkdir -p ${OEM_QWES_OVERRIDE_LICENSE_STORE}

if [ -d "${OEM_QWES_OVERRIDE_LICENSE_STORE}" ]; then

    chmod o+rwx "${OEM_QWES_OVERRIDE_LICENSE_STORE}"
    chmod o+rwx "${PFM_PATH}"

    files=$(ls /var/cache/qwes/*.pfm 2> /dev/null | wc -l)
    if [ "$files"  != "0" ]; then
         echo "Source location content" > /dev/kmsg
         ls /var/cache/qwes/ > /dev/kmsg
         echo "Copying licenses to license store location" > /dev/kmsg
         cp /var/cache/qwes/*.pfm "${OEM_QWES_OVERRIDE_LICENSE_STORE}" > /dev/kmsg
         sync
         echo "Copy status is $?" > /dev/kmsg
         chown system:system "${OEM_QWES_OVERRIDE_LICENSE_STORE}"/*.pfm
         echo "Destination location content" > /dev/kmsg
         ls -l "${OEM_QWES_OVERRIDE_LICENSE_STORE}" > /dev/kmsg
         echo "Removing Source location files" > /dev/kmsg
         rm -rf /var/cache/qwes/*.pfm
    fi
    chown system:system -R /var/cache/qwes/
 else
    echo "Failed to create License store!!!"  > /dev/kmsg
fi

