#!/bin/sh
#==============================================================================
# FILE: sfs_config
#
# DESCRIPTION:
# create files and give permissions to the files and directories needed by
# secure file system
#
# Copyright (c) 2017, 2023-2024 Qualcomm Technologies, Inc.
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#==============================================================================
set -e

if [ -e /var/persist ]; then
    if [ ! -d /var/persist/qtee_supplicant ]; then
         echo "Creating /var/persist/qtee_supplicant"
         mkdir -p /var/persist/qtee_supplicant
    fi
    chmod o+rwx /var/persist/qtee_supplicant
fi

if [ ! -d /var/tmp/qtee_supplicant/vendor/tzstorage ]; then
    echo "Creating /var/tmp/qtee_supplicant/vendor/tzstorage"
    mkdir -p /var/tmp/qtee_supplicant/vendor/tzstorage
fi
chmod o+rwx /var/tmp/qtee_supplicant/vendor/tzstorage

exit 0
