# yaml-language-server: $schema=https://raw.githubusercontent.com/siemens/kas/master/kas/schema-kas.json

header:
  version: 14

distro: nodistro

defaults:
  repos:
    branch: master

repos:
  meta-qcom-hwe:

  meta-qcom:
    url: https://github.com/Linaro/meta-qcom

  oe-core:
    url: https://git.openembedded.org/openembedded-core
    layers:
      meta:

  bitbake:
    url: https://git.openembedded.org/bitbake
    layers:
      .: excluded

local_conf_header:
  base: |
    CONF_VERSION = "2"
    INIT_MANAGER = "systemd"
    PACKAGE_CLASSES = "package_ipk"
    INHERIT += "buildstats buildstats-summary"
    INHERIT += "buildhistory"
    INHERIT += "rm_work"
  qcomflash: |
    IMAGE_CLASSES += "image_types_qcom"
    IMAGE_FSTYPES += "qcomflash"
  extra: |
    EXTRA_IMAGE_FEATURES = "allow-empty-password empty-root-password allow-root-login"
    IMAGE_ROOTFS_EXTRA_SPACE = "307200"

machine: unset

target:
  - core-image-base
