#!/bin/sh
########################################################################
#Copyright (c) 2017, The Linux Foundation. All rights reserved.
#
#Redistribution and use in source and binary forms, with or without
#modification, are permitted provided that the following conditions are
#met:
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials provided
#      with the distribution.
#    * Neither the name of The Linux Foundation nor the names of its
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
#
#THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
#WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
#ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
#BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
#BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
#OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
#IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#########################################################################

### BEGIN INIT INFO
# Provides: weston
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

if test -e /etc/default/weston ; then
        . /etc/default/weston
fi

killproc() {
        pid=`/bin/pidof $1`
        [ "$pid" != "" ] && kill $pid
}

launch_weston=`getprop persist.display.launch.weston.at.bootup`

read CMDLINE < /proc/cmdline
for x in $CMDLINE; do
        case $x in
        weston=false)
        echo "Weston disabled"
        exit 0;
                ;;
        esac
done

case "$1" in
  start)
        . /etc/profile

        # This is all a nasty hack
        if test -z "$XDG_RUNTIME_DIR"; then
            export XDG_RUNTIME_DIR=/run/user/root
            mkdir -p $XDG_RUNTIME_DIR
            chmod 0700 $XDG_RUNTIME_DIR
        fi

        if test -z "$XDG_PICTURES_DIR"; then
            export XDG_PICTURES_DIR=/data/misc/display
        fi

        if [[ -z "$SHELL" && -x "/bin/sh" ]]; then
            export SHELL=/bin/sh
        fi

        echo "WESTON INITIALIZATION STARTUP"
        weston --tty=2 --idle-time=0 --log=/tmp/weston.log --config=/etc/xdg/weston/weston.ini \
        --continue-without-input &

        # Wait wayland socket node create.
        filename=$(find $XDG_RUNTIME_DIR -maxdepth 1 -name 'wayland-*' -print -quit)
        while [ -z "$filename" ]; do
            sleep 0.1
            filename=$(find $XDG_RUNTIME_DIR -maxdepth 1 -name 'wayland-*' -print -quit)
        done

        chown -hR system:video $XDG_RUNTIME_DIR
        chmod 756 /run/user/root/wayland-1
  ;;

  stop)
        echo "Stopping Weston"
        killproc weston
  ;;

  restart)
    $0 stop
        sleep 1
        $0 start
  ;;

  *)
        echo "usage: $0 { start | stop | restart }"
  ;;
esac

exit 0
